runtime: python310
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  FLASK_ENV: production
  SECRET_KEY: "TU_CLAVE_SECRETA_AQUI"
  JWT_SECRET_KEY: "TU_CLAVE_JWT_AQUI"
  CORS_ORIGINS: "https://nexify.com.es"

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto


